services:
  opentelemetry:
    image: "otel/opentelemetry-collector:latest"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: "--config=/etc/otel-collector-config.yaml"
    ports:
      - 4317:4317
    networks:
      - otel-jaeger-network
    depends_on:
      - Jaeger
      
  Jaeger:
    image: "jaegertracing/all-in-one"
    container_name: Jaeger
    environment:
      - "-e COLLECTOR_OTLP_ENABLED=true"
      - "-e COLLECTOR_OTLP_GRPC_TLS_ENABLED=flase"
    ports:
      - 16686:16686
      - 14268:14268 
      - 14250:14250 
    networks:
      - otel-jaeger-network

networks:
  otel-jaeger-network:
    driver: bridge

